# Generated by Django 6.0.3 on 2026-03-31 17:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], default='buy', max_length=50)),
                ('value', models.PositiveIntegerField()),
                ('price_per_unit', models.PositiveIntegerField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='portfolio.portfolio')),
            ],
        ),
    ]
