# Generated by Django 6.0.3 on 2026-04-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
        ('portfolio', '0005_portfolioasset_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа'), ('accrual', 'Начисление'), ('debit', 'Списание'), ('add', 'Пополнение'), ('withdraw', 'Вывод')], default='buy', max_length=50),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('accrual', 'Начисление'), ('debit', 'Списание')], default='accrual', max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='portfolio.portfolio')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('add', 'Пополнение'), ('withdraw', 'Вывод')], default='add', max_length=50)),
                ('value', models.FloatField()),
                ('time_stamp', models.DateTimeField(auto_now_add=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='portfolio.portfolio')),
            ],
        ),
    ]
