# Generated by Django 6.0.3 on 2026-04-13 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0002_alter_deal_type_payment_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deals',
            name='type',
            field=models.CharField(choices=[('buy', 'Покупка'), ('sell', 'Продажа')], default='buy', max_length=50),
        ),
    ]
