# Generated by Django 6.0.3 on 2026-04-02 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='type',
            field=models.CharField(choices=[('mixed', 'mixed'), ('crypto', 'crypto'), ('stock_market', 'stock_market'), ('stock_market_rus', 'stock_market_rus'), ('stock_market_us', 'stock_market_us'), ('raw_material', 'raw_material')], default='mixed', max_length=30),
        ),
    ]
