# Generated by Django 6.0.3 on 2026-04-03 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfolio_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='external_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
