# Generated by Django 6.0.3 on 2026-03-19 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='count',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='portfolio',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='purchase_price_per_unit',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='time_stamp',
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.CreateModel(
            name='PortfolioAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField()),
                ('avg_purchase_price', models.FloatField()),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset', to='portfolio.asset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='portfolio.portfolio')),
            ],
            options={
                'unique_together': {('portfolio', 'asset')},
            },
        ),
    ]
