# Generated by Django 6.0.3 on 2026-03-27 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_remove_asset_count_remove_asset_portfolio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioasset',
            old_name='avg_purchase_price',
            new_name='price',
        ),
    ]
