# Generated by Django 6.0.3 on 2026-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioasset',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
