# Generated by Django 6.0.3 on 2026-04-12 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_portfolioasset_balance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolioasset',
            name='balance',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='balance',
            field=models.FloatField(default=0),
        ),
    ]
